/**
 * Demo Data for Mayu Hub
 * Used for development and testing before Supabase integration
 */

import type { Neighborhood, StoreProfile, CommunityService, BannerAd, ServiceCategory } from './types'

// 36 Neighborhoods of 15 May City
export const demoNeighborhoods: Neighborhood[] = Array.from({ length: 36 }, (_, i) => ({
  id: `neighborhood-${i + 1}`,
  nameAr: `المجاورة ${i + 1}`,
  number: i + 1,
  isActive: i < 6, // First 6 are active for MVP
}))

// Adjacency map (simplified - each neighborhood adjacent to ±1, ±2)
export const demoAdjacencyMap = new Map<string, string[]>(
  demoNeighborhoods.map(n => [
    n.id,
    demoNeighborhoods
      .filter(other => {
        const diff = Math.abs(other.number - n.number)
        return diff > 0 && diff <= 3
      })
      .map(other => other.id)
  ])
)

export const demoCategories: ServiceCategory[] = [
  { id: 'cat-pharmacy', nameAr: 'صيدلية', icon: '💊', sortOrder: 1, isActive: true },
  { id: 'cat-supermarket', nameAr: 'سوبر ماركت', icon: '🛒', sortOrder: 2, isActive: true },
  { id: 'cat-butcher', nameAr: 'جزار', icon: '🥩', sortOrder: 3, isActive: true },
  { id: 'cat-barber', nameAr: 'حلاق', icon: '💈', sortOrder: 4, isActive: true },
  { id: 'cat-restaurant', nameAr: 'مطعم', icon: '🍽️', sortOrder: 5, isActive: true },
  { id: 'cat-bakery', nameAr: 'مخبز', icon: '🍞', sortOrder: 6, isActive: true },
  { id: 'cat-electronics', nameAr: 'إلكترونيات', icon: '📱', sortOrder: 7, isActive: true },
  { id: 'cat-clothing', nameAr: 'ملابس', icon: '👕', sortOrder: 8, isActive: true },
]

export const demoStores: StoreProfile[] = [
  {
    id: 'store-1',
    ownerId: 'owner-1',
    neighborhoodId: 'neighborhood-1',
    nameAr: 'صيدلية الشفاء',
    phone: '+201012345678',
    whatsappNumber: '+201012345678',
    whatsappMessage: 'مرحباً، أريد الاستفسار عن دواء',
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-pharmacy',
    isPremium: true,
    premiumStartedAt: '2025-01-01T00:00:00Z',
    premiumExpiresAt: '2026-01-01T00:00:00Z',
    status: 'approved',
    rejectionReason: null,
    delivers: true,
    deliveryCostEgp: 15,
    deliveryDurationMinutes: 30,
    manualStatusOverride: null,
    manualStatusOverrideUntil: null,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'store-2',
    ownerId: 'owner-2',
    neighborhoodId: 'neighborhood-1',
    nameAr: 'سوبر ماركت النور',
    phone: '+201098765432',
    whatsappNumber: '+201098765432',
    whatsappMessage: 'مرحباً، عايز أطلب توصيل',
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-supermarket',
    isPremium: false,
    premiumStartedAt: null,
    premiumExpiresAt: null,
    status: 'approved',
    rejectionReason: null,
    delivers: true,
    deliveryCostEgp: 10,
    deliveryDurationMinutes: 45,
    manualStatusOverride: null,
    manualStatusOverrideUntil: null,
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'store-3',
    ownerId: 'owner-3',
    neighborhoodId: 'neighborhood-2',
    nameAr: 'جزارة الأمين',
    phone: '+201155544433',
    whatsappNumber: null,
    whatsappMessage: null,
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1588347818036-558601350947?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-butcher',
    isPremium: false,
    premiumStartedAt: null,
    premiumExpiresAt: null,
    status: 'approved',
    rejectionReason: null,
    delivers: false,
    deliveryCostEgp: null,
    deliveryDurationMinutes: null,
    manualStatusOverride: null,
    manualStatusOverrideUntil: null,
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'store-4',
    ownerId: 'owner-4',
    neighborhoodId: 'neighborhood-2',
    nameAr: 'حلاق الأناقة',
    phone: '+201234567890',
    whatsappNumber: '+201234567890',
    whatsappMessage: 'عايز أحجز ميعاد',
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-barber',
    isPremium: true,
    premiumStartedAt: '2025-02-01T00:00:00Z',
    premiumExpiresAt: '2026-02-01T00:00:00Z',
    status: 'approved',
    rejectionReason: null,
    delivers: false,
    deliveryCostEgp: null,
    deliveryDurationMinutes: null,
    manualStatusOverride: 'open',
    manualStatusOverrideUntil: null,
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'store-5',
    ownerId: 'owner-5',
    neighborhoodId: 'neighborhood-3',
    nameAr: 'مطعم البيت',
    phone: '+201111222333',
    whatsappNumber: '+201111222333',
    whatsappMessage: 'عايز أطلب أكل',
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-restaurant',
    isPremium: false,
    premiumStartedAt: null,
    premiumExpiresAt: null,
    status: 'approved',
    rejectionReason: null,
    delivers: true,
    deliveryCostEgp: 20,
    deliveryDurationMinutes: 40,
    manualStatusOverride: null,
    manualStatusOverrideUntil: null,
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'store-6',
    ownerId: 'owner-6',
    neighborhoodId: 'neighborhood-3',
    nameAr: 'مخبز السعادة',
    phone: '+201444555666',
    whatsappNumber: null,
    whatsappMessage: null,
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-bakery',
    isPremium: false,
    premiumStartedAt: null,
    premiumExpiresAt: null,
    status: 'approved',
    rejectionReason: null,
    delivers: false,
    deliveryCostEgp: null,
    deliveryDurationMinutes: null,
    manualStatusOverride: null,
    manualStatusOverrideUntil: null,
    createdAt: '2025-03-15T00:00:00Z',
    updatedAt: '2025-03-15T00:00:00Z',
  },
  {
    id: 'store-7',
    ownerId: 'owner-7',
    neighborhoodId: 'neighborhood-4',
    nameAr: 'صيدلية الحياة',
    phone: '+201777888999',
    whatsappNumber: '+201777888999',
    whatsappMessage: 'مرحباً، محتاج استشارة',
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-pharmacy',
    isPremium: false,
    premiumStartedAt: null,
    premiumExpiresAt: null,
    status: 'approved',
    rejectionReason: null,
    delivers: true,
    deliveryCostEgp: 10,
    deliveryDurationMinutes: 25,
    manualStatusOverride: null,
    manualStatusOverrideUntil: null,
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2025-04-01T00:00:00Z',
  },
  {
    id: 'store-8',
    ownerId: 'owner-8',
    neighborhoodId: 'neighborhood-5',
    nameAr: 'سوبر ماركت الخير',
    phone: '+201000111222',
    whatsappNumber: '+201000111222',
    whatsappMessage: 'عايز أطلب',
    logoUrl: null,
    storefrontPhotoUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&h=250&fit=crop&q=80',
    categoryId: 'cat-supermarket',
    isPremium: false,
    premiumStartedAt: null,
    premiumExpiresAt: null,
    status: 'approved',
    rejectionReason: null,
    delivers: true,
    deliveryCostEgp: 12,
    deliveryDurationMinutes: 35,
    manualStatusOverride: null,
    manualStatusOverrideUntil: null,
    createdAt: '2025-04-15T00:00:00Z',
    updatedAt: '2025-04-15T00:00:00Z',
  },
]

export const demoCommunityServices: CommunityService[] = [
  { id: 'cs-1', neighborhoodId: 'neighborhood-1', nameAr: 'مدرسة 15 مايو الابتدائية', type: 'school', schoolType: 'government', address: 'شارع المدرسة، المجاورة 1', phone: '+20225551234' },
  { id: 'cs-2', neighborhoodId: 'neighborhood-1', nameAr: 'مسجد الرحمن', type: 'mosque', schoolType: null, address: 'الشارع الرئيسي، المجاورة 1', phone: null },
  { id: 'cs-3', neighborhoodId: 'neighborhood-2', nameAr: 'مستشفى 15 مايو العام', type: 'hospital', schoolType: null, address: 'شارع المستشفى، المجاورة 2', phone: '+20225559876' },
  { id: 'cs-4', neighborhoodId: 'neighborhood-2', nameAr: 'مكتب بريد المجاورة 2', type: 'post_office', schoolType: null, address: 'ميدان البريد', phone: '+20225554321' },
  { id: 'cs-5', neighborhoodId: 'neighborhood-3', nameAr: 'مدرسة النيل التجريبية', type: 'school', schoolType: 'experimental', address: 'شارع النيل، المجاورة 3', phone: '+20225557777' },
  { id: 'cs-6', neighborhoodId: 'neighborhood-3', nameAr: 'مركز شباب 15 مايو', type: 'youth_center', schoolType: null, address: 'شارع الشباب', phone: '+20225558888' },
  { id: 'cs-7', neighborhoodId: 'neighborhood-4', nameAr: 'قسم شرطة 15 مايو', type: 'police_station', schoolType: null, address: 'الشارع الرئيسي، المجاورة 4', phone: '+20225550000' },
  { id: 'cs-8', neighborhoodId: 'neighborhood-5', nameAr: 'مكتب غاز المجاورة 5', type: 'gas_office', schoolType: null, address: null, phone: '+20225551111' },
]

export const demoBanners: BannerAd[] = [
  {
    id: 'banner-1',
    imageUrl: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&h=200&fit=crop&q=80',
    targetType: 'store',
    targetStoreId: 'store-1',
    targetUrl: null,
    startsAt: '2025-01-01',
    endsAt: '2026-12-31',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'banner-2',
    imageUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&h=200&fit=crop&q=80',
    targetType: 'store',
    targetStoreId: 'store-2',
    targetUrl: null,
    startsAt: '2025-01-01',
    endsAt: '2026-12-31',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'banner-3',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=200&fit=crop&q=80',
    targetType: 'external',
    targetStoreId: null,
    targetUrl: 'https://example.com',
    startsAt: '2025-01-01',
    endsAt: '2026-12-31',
    isActive: true,
    sortOrder: 3,
  },
]

// Demo working hours (all stores open 9am-10pm Saturday-Thursday)
export const demoWorkingHours = demoStores.map(store => 
  [6, 0, 1, 2, 3, 4].map(day => ({ // Sat=6, Sun=0, Mon=1...Thu=4
    id: `wh-${store.id}-${day}`,
    storeId: store.id,
    dayOfWeek: day,
    openTime: '09:00',
    closeTime: '22:00',
    isClosed: false,
  }))
).flat()
